# Generated by Django 2.2.3 on 2020-02-23 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='url',
            new_name='freq',
        ),
        migrations.RenameField(
            model_name='freq',
            old_name='ul',
            new_name='ulink',
        ),
    ]
